// This file was auto-generated by NetBeans IDE (ignore these two lines)
// Click the links above to change the license or edit the template

// Declares that this class belongs to the "CA_2" package (folder/group)
package CA_2;

// Defines a public class called Manager
public class Manager {

    // Defines an enum (a fixed list of named options) called ManagerType
    public enum ManagerType {

        // First option: Senior Manager, linked to number 1 and the text "Senior Manager"
        SENIOR_MANAGER(1, "Senior Manager"),
        // Second option: Manager, linked to number 2 and the text "Manager"
        MANAGER(2, "Manager"),
        // Third option: Junior Manager, linked to number 3 and the text "Junior Manager"
        JUNIOR_MANAGER(3, "Junior Manager");

        // Stores the number (1, 2, or 3) for each manager type — cannot be changed
        private final int option;
        // Stores the display text (e.g. "Senior Manager") — cannot be changed
        private final String label;

        // Constructor for the enum — runs when each option above is created
        ManagerType(int option, String label) {
            this.option = option; // Saves the number into this enum value
            this.label  = label;  // Saves the text into this enum value
        }

        // Returns the number (option) for this manager type
        public int getOption()  { return option; }
        // Returns the display text (label) for this manager type
        public String getLabel() { return label; }

        // Finds a ManagerType by its number — e.g. passing 2 returns MANAGER
        public static ManagerType fromInt(int value) {
            // Loops through every ManagerType value (SENIOR_MANAGER, MANAGER, JUNIOR_MANAGER)
            for (ManagerType type : values()) {
                // If this type's number matches the one we're looking for, return it
                if (type.getOption() == value) return type;
            }
            return null; // If no match was found, return null (invalid choice)
        }

        // Finds a ManagerType by its text label — e.g. passing "manager" returns MANAGER
        public static ManagerType fromString(String label) {
            // Loops through every ManagerType value
            for (ManagerType type : values()) {
                // Compares ignoring uppercase/lowercase and extra spaces
                if (type.getLabel().equalsIgnoreCase(label.trim())) return type;
            }
            return null; // If no match was found, return null (not found)
        }
    }

    // ================================================================
    //  FIELDS
    // ================================================================
    private String name;        // Stores the manager's full name
    private ManagerType type;   // Stores the manager's type (Senior, Manager, or Junior)
    private String department;  // Stores the department this manager belongs to

    // ================================================================
    //  CONSTRUCTOR
    // ================================================================
    // Creates a new Manager object with a name, type, and department
    public Manager(String name, ManagerType type, String department) {
        this.name       = name;       // Saves the given name into this object
        this.type       = type;       // Saves the given type into this object
        this.department = department; // Saves the given department into this object
    }

    // ================================================================
    //  GETTERS
    // ================================================================
    // Returns the manager's name
    public String getName()       { return name; }
    // Returns the manager's type as a ManagerType enum value
    public ManagerType getType()  { return type; }
    // Returns the manager's type as readable text (e.g. "Senior Manager")
    public String getTypeLabel()  { return type.getLabel(); }
    // Returns the manager's department
    public String getDepartment() { return department; }

    // Prints all available manager types to the terminal
    // Used when adding a new record so the user can pick a type
    public static void displayManagerTypes() {
        // Prints a heading before the list
        System.out.println("\nPlease select from the following Manager Types:");
        // Loops through every ManagerType and prints its number and label
        for (ManagerType type : ManagerType.values()) {
            System.out.println(type.getOption() + ". " + type.getLabel()); // e.g. "1. Senior Manager"
        }
    }

    // Returns a nicely formatted single-line summary of this manager
    // Columns are padded so they line up in a table
    @Override
    public String toString() {
        // %-20s = left-align name in 20 chars | %-18s = left-align type in 18 chars | department with no padding
        return String.format("%-20s | %-18s | %s", name, type.getLabel(), department);
    }
}